### PR TITLE
added all contributors badge to README

### PR DESCRIPTION
**Pull request by chrissimpkins**
PR includes: 

- new all contributors # style badge on the README page
- badge links to Contributors list on README page

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Closes #21

**Comment by kentcdodds** [comment]
Maybe we should add in there something that indicates you don't need the badge to comply the spec. Maybe put this in the optional section. And also we could say you could do the version of the badge that doesn't have a number of contributors you have to maintain...

**Comment by chrissimpkins** [comment]
See #15.  I just suggested that we have a detailed look at the wording and perhaps rephrase the current mandatory / optional items in the spec.  Perhaps this could fall under a "Guidelines for Implementation" category that is optional for projects?

**Comment by kentcdodds** [comment]
:+1: to that

**Comment by jfmengels** [comment]
LGTM :+1:

**Comment by Jameskmonger** [comment]
Nice one @chrissimpkins ! :smile:

**Comment by chrissimpkins** [comment]
:+1:

**Pull request merged**
