### PR TITLE
feat(content): adds content writers as a contributor type

### PR DESCRIPTION
**Pull request by Frijol**

### CODE REVIEW

**Comment by Frijol** [comment]
Copy for a website– e.g. all the text of a homepage, an "about us" page, etc. Would "copy" be better?

**Comment by kentcdodds** [comment]
Thanks, but I'd personally consider that to fall under "docs"

**Comment by Frijol** [comment]
Isn't "docs" fairly strictly defined to documentation of e.g. an API, policy, process? Writing the copy on a persistent page is something more akin to design/marketing

**Comment by kentcdodds** [comment]
Thanks!

**Pull request merged**
