### PR TITLE
Added Spanish documetation of the project

### PR DESCRIPTION
**Pull request by robertlluberes**
The Spanish version was added for project documentation. I think it can be improved, but it's a good start (I'm a native Spanish speaker)

### CODE REVIEW

**Comment by MatheusRV** [comment]
@kentcdodds @robertlluberes We have to think how to keep the contributors table with data consistency, any suggestions? My vote and for keeping just the readme and the languages redirect to it.

**Comment by kentcdodds** [comment]
> My vote and for keeping just the readme and the languages redirect to it.

I agree

**Comment by robertlluberes** [comment]
> My vote and for keeping just the readme and the languages redirect to it.

I agree too. I will redirect the Spanish version to the section Contributors in the README file of the root path of the repo to keep it centralized.

**Comment by MatheusRV** [comment]
PT-BR done, write a text explain. See pt br.

**Pull request merged**
