### PR TITLE
Sort emoji key alphanumerically

### PR DESCRIPTION
**Pull request by patcon**
Hello! I just found out about this project and it is truly amazing, and I am so grateful for all the thought put into this!

One thing that struck me (neither as particularly good or bad, but just "noticed") was that the emoji key is sorted somewhat arbitrarily. "Code" happens to be the first item.

I suspect it's just the order things were added, or some such, but it does seem like an odd little signal which seems counter to the spirit of the project :)

Would you be willing to accept a re-sort?

### CODE REVIEW

**Comment by patcon** [comment]
Meh, just did it. No hard feelings if you have other preferences ;)

**Comment by kentcdodds** [comment]
Thank you so much!

**Comment by kentcdodds** [comment]
Would you like to [add yourself](https://github.com/kentcdodds/all-contributors/blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)? Feel free to open another PR for that.

**Comment by patcon** [comment]
oh! yeah, haha, will do! ;)

(I'm clearly new to this mode of thinking... haha)

**Pull request merged**
