### PR TITLE
New Markdown collaborator list templates

### PR DESCRIPTION
**Pull request by chrissimpkins**
PR includes:

- New `examples/markdown.md` Markdown template gallery + collaborator list markup to simplify manual implementation and provide recommended collaborator list examples
- New link from `README.md` to the `examples/markdown.md` page

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Addresses issue #15

**Comment by kentcdodds** [comment]
I think that we should show 7 columns. That's as wide as GitHub will let us do. You can add @frigginglorious for the 7th column :-)

For the 4 columns, I think you could make the images bigger or something. Not sure I see any other reason to not go with full width (7).

**Comment by chrissimpkins** [comment]
- [X] Seven columns
- [X] larger images in 4 column template

:+1:

**Comment by chrissimpkins** [comment]
This probably warrants a link to your example of how to find contributor avatar images and modify the image size.

**Comment by kentcdodds** [comment]
Another thing, for the 4 column template, that should probably not put the names in a `<sub>` because there's enough room for the full text size.

Also, feel free to add a link to the TIPS :+1:

**Comment by jfmengels** [comment]
I don't understand the use of less than full-width tables. I find it nice-looking even when there are few contributors. And when there are more contributors (and as pretty much anything is considered a contribution, seems pretty likely).

Also, I don't want people to reorganize everything manually if they get more contributors than expected... :s

**Comment by kentcdodds** [comment]
Yeah, honestly, I'm only really in support of the one format this project uses (7 columns). The other two take up too much space IMO

**Comment by chrissimpkins** [comment]
Removed the single and four columns template examples.  It is now a seven column template only.

**Comment by kentcdodds** [comment]
Cool!

Honestly, I think we'll be able to remove this as soon as this project has enough contributors though. Because at that point, this project itself can be the example.

But I'm good to merge it now.

Waiting for another maintainer to check off on this here and click the merge button :-)

**Comment by chrissimpkins** [comment]
What is your thought to a change to this example layout instead?

collabs

Will include more of the emjoi examples and fake collaborator names.  Will then include a link to the TIPS.md to learn how to find your GitHub avatar to replace the placeholder images.

**Comment by jfmengels** [comment]
@chrissimpkins I'm sorry, but I don't see the difference with what is currently in the project README.md (except the more colorful emojis) :s
Can you elaborate on the differences?

**Comment by chrissimpkins** [comment]
@jfmengels Kent was interested in providing a recommended approach to the list layout that exists outside of the specification.  The goal here would be to provide an example of the Markdown that is used in a code block on the page along with a link to the TIPS.md page so that users can learn how to obtain GitHub avatars and size them (or consolidate this to a single page).  It is basically the manual list construction cheat sheet.  I am assuming that manual list maintenance will be common among smaller projects.   Yes it will be possible to view the raw project README file to try to gather this information but I find this to be a simpler approach from a user standpoint.

**Comment by chrissimpkins** [comment]
Something that I haven't considered is that we will have the opportunity to use more of the emoji in the examples than in the project page.  Users can then determine whether they like this layout.   It is definitely colorful and they may opt for custom indicators with a bit more similarity in their design (or we could try to attract a designer to make custom icons and serve those instead).

**Comment by chrissimpkins** [comment]
And to followup the last comment, as I have  worked on this it appears that any more than 3 icons are going to cause the layout to break.  Something else to consider.  Perhaps an alternative letter indicator approach will work for projects that have contributors that cross a broad range of these categories.

**Comment by kentcdodds** [comment]
> it appears that any more than 3 icons are going to cause the layout to break

That concerns me. Perhaps we should make the table only 6 columns wide to account for this and longer names (as @fhemberger had to abbreviate his first name to not break layout :frowning:). Thoughts? :thought_balloon: 

> Yes it will be possible to view the raw project README file to try to gather this information but I find this to be a simpler approach from a user standpoint.

I'm all for having this file for this reason.

**Comment by chrissimpkins** [comment]
Paused for additional discussion in #15

**Pull request closed without merging**
