### PR TITLE
Add Emoji for "Translation"

### PR DESCRIPTION
**Pull request by fhemberger**
May be translated documentation or international community sites

### CODE REVIEW

**Comment by kentcdodds** [comment]
Oh! This is a great suggestion!

Do you mind adding yourself to the list of contributors as well?

**Comment by fhemberger** [comment]
@kentcdodds Added myself as contributor. Adding my first name will break the table layout. ;)

**Comment by kentcdodds** [comment]
Ah! I was afraid of that! Oh well! This is good to merge! Anyone want to check it and click the button?

**Comment by chrissimpkins** [comment]
Looks great!

Thoughts on the organization of the Categories list?  Should we alphabetize it?  Will merge and we can discuss in a separate issue report.

**Pull request merged**
