### PR TITLE
add ✨ to make the title less boring.

### PR DESCRIPTION
**Pull request by kentcdodds**
Thoughts? :thought_balloon:

### CODE REVIEW

**Comment by kentcdodds** [comment]
Preview [here](https://github.com/kentcdodds/all-contributors/blob/kentcdodds-patch-1/README.md)

screen shot 2016-03-01 at 8 12 28 pm

**Comment by kentcdodds** [comment]
We can revert this later if people don't like it, but this repo is getting a lot of attention right now on twitter, so I'd like to go ahead and merge this.

If people could comment in here to let me know if you'd like to revert, please do!

**Comment by jfmengels** [comment]
It looks fine to me

**Comment by Jameskmonger** [comment]
Looks good to me! Not sure why the emojis aren't colourful though...

heading screenshot

**Comment by kentcdodds** [comment]
Are you in Windows?

**Comment by jfmengels** [comment]
image
Linux Ubuntu - Chrome

**Comment by Jameskmonger** [comment]
Windows 8.1 Pro - Chrome `48.0.2564.116 m`

**Comment by ewnd9** [comment]
I have an almost normal once on Ubuntu 14.04 (two sizes small than title) 
image

According to html sources below, I may assume some javascript on github has a false positive detection of a system support of emoji in some cases  
 
image

**Comment by kentcdodds** [comment]
Ah, interesting...

**Comment by ewnd9** [comment]
I've submitted a WIP pull request #25, @Jameskmonger @jfmengels could you test does readme display images instead of Unicode symbols, please?

I think it would be nice to always stick to ":emoji:" anyways for better accessibility @kentcdodds 

Example: 
image

**Pull request merged**
