### PR TITLE
fix odd wording

### PR DESCRIPTION
**Pull request by kentcdodds**
This was originally created in #17 by @frigginglorious and the commit has been attributed to him.

Could someone else click the merge button?

### CODE REVIEW

**Comment by kentcdodds** [comment]
With this pr, it puts us on a newline :-)

screen shot 2016-03-02 at 8 36 36 am

**Comment by kentcdodds** [comment]
:tada: thanks @frigginglorious!

**Comment by frigginglorious** [comment]
Haha, thanks @kentcdodds I'm bad with git sometimes. I saw you post that Contributing to OS tutorial link on twitter a bit ago, and I think I need to watch the whole thing :P

**Comment by kentcdodds** [comment]
I hope it's helpful!

**Pull request merged**
