### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### kentcdodds/all-contributors now has a Chat Room on Gitter

@jfmengels has just created a chat room. You can visit it here: [https://gitter.im/kentcdodds/all-contributors](https://gitter.im/kentcdodds/all-contributors?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/kentcdodds/all-contributors?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by kentcdodds** [comment]
Anyone opposed to using this one instead?

Gitter badge

**Comment by ben-eb** [comment]
@kentcdodds Yes, the Gitter green distinguishes it from the continuous integration services.

**Comment by kentcdodds** [comment]
True, how about this then:

Gitter badge

**Comment by kentcdodds** [comment]
I just love the flat square :-)

**Comment by Jameskmonger** [comment]
I like that flat square with the Gitter green @kentcdodds

**Comment by ben-eb** [comment]
I tend to prefer the default one as it integrates nicely with GitHub's aesthetic. But I don't feel that strongly either way.

**Comment by chrissimpkins** [comment]
They all look good :+1:

**Comment by jfmengels** [comment]
Don't really care, do what you want :)

**Comment by jfmengels** [comment]
Now... the biggest question is...

Is gitter-badger now a contributor and should he be added to the contributors' list? :D

**Comment by chrissimpkins** [comment]
> Is gitter-badger now a contributor and should he be added to the contributors' list? :D

Haha! +1

**Comment by jfmengels** [comment]
I say, if he answers and wants to, let's add him! @gitter-badger, do you want to be marked as a contributor? :D

**Pull request closed without merging**
